# -*- coding: utf-8 -*-
"""1908012_1908029_ ETE-430 Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kmnEIHN96-sumfpi4sjF7F4knvCm69Vy

#parkinson disease detection using RNN, CNN, Ensemble methods
"""

#mount Google
from google.colab import drive
drive.mount('/content/drive')

"""Dataset source:   Max A. Little, Patrick E. McSharry, Eric J. Hunter, Lorraine O. Ramig (2008), 'Suitability of dysphonia measurements for telemonitoring of Parkinson's disease', IEEE Transactions on Biomedical Engineering (to appear).

IMPORT IMPORTANT LIBRARIES
"""

import numpy as np
import pandas as pd
import math
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns
from sklearn.manifold import TSNE
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, VotingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

"""#load Dataset

"""

data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/parkinsons.data", sep=',', index_col='name')
data

"""#Pre processing

"""

#exclude "status" and  from the feature set
X = data.drop('status', axis=1)
# make "status as lebel"
y=data['status']
data.head()

#check for missing value
data.isnull().sum()

y.head()



"""#KNN Model"""

#KNN Model
# Reshape X_train and X_test to 2D for KNN
X_train_knn = X_train.reshape(X_train.shape[0], -1)
X_test_knn = X_test.reshape(X_test.shape[0], -1)

# Convert one-hot encoded y_train and y_test back to single-column labels for KNN
y_train_knn = np.argmax(y_train, axis=1)
y_test_knn = np.argmax(y_test, axis=1)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_knn, y_train_knn)  # Use reshaped data for KNN
knn_pred = knn.predict(X_test_knn)  # Use reshaped data for KNN
print("knn Accuracy:", accuracy_score(y_test_knn,knn_pred))  # Use original labels for evaluation
print("\nClassification Report:\n", classification_report(y_test_knn, knn_pred))  # Use original labels for evaluation

X.shape

X.info()

"""#ensembles

##Bagging
"""

# Reshape X_train and X_test to 2D
X_train = X_train.reshape(X_train.shape[0], -1) # -1 infers the remaining dimension
X_test = X_test.reshape(X_test.shape[0], -1)   # -1 infers the remaining dimension

# 1. Bagging with Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
print("Bagging (Random Forest) Accuracy:")
print("\nClassification Report:\n", classification_report(y_test, rf_pred))
print("\nAccuracy Score:", accuracy_score(y_test, rf_pred))

"""##Boosting"""

# Convert y_train to a 1D array if it's one-hot encoded
import numpy as np
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

# Assuming y_test is in multilabel-indicator format, convert to binary format
if y_test.ndim == 2 and y_test.shape[1] > 1:  # Check if y_test is one-hot encoded
    y_test = np.argmax(y_test, axis=1)  # Convert to 1D array of class labels

if y_train.ndim == 2 and y_train.shape[1] > 1:  # Check if y_train is one-hot encoded
    y_train = np.argmax(y_train, axis=1)  # Convert to 1D array of class labels

# 2. Boosting with AdaBoost
ada_model = AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=2),
    n_estimators=150,
    learning_rate=0.5,
    random_state=42)
ada_model.fit(X_train, y_train)  # Now y_train should be 1D
ada_pred = ada_model.predict(X_test)
print("Boosting (AdaBoost) Accuracy:", accuracy_score(y_test, ada_pred))
print("\nClassification Report:\n", classification_report(y_test, ada_pred))

"""##Voting model"""

# 3. Voting Classifier
log_model = LogisticRegression(max_iter=1000, random_state=42)
dt_model = DecisionTreeClassifier(random_state=42)
svc_model = SVC(probability=True,gamma=10, C=1000, random_state=42)

voting_model = VotingClassifier(
    estimators=[("lr", log_model), ("dt", dt_model), ("svc", svc_model),("rf", rf_model),
        ("knn", knn)],
    voting="soft"  # Use 'soft' for probability-based voting
)
voting_model.fit(X_train, y_train)
voting_pred = voting_model.predict(X_test)
print("Voting Classifier Accuracy:", accuracy_score(y_test, voting_pred))
print("\nClassification Report:\n", classification_report(y_test, voting_pred))

"""##voting again with tuned decision tree and logistic regression"""

from sklearn.model_selection import GridSearchCV

# Set up the parameter grid for Logistic Regression
log_param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['lbfgs', 'liblinear']
}

# Run GridSearchCV for Logistic Regression
log_grid_search = GridSearchCV(LogisticRegression(max_iter=1000, random_state=42), log_param_grid, cv=5, scoring='accuracy')
log_grid_search.fit(X_train, y_train)

print("Best Logistic Regression params:", log_grid_search.best_params_)
print("Best Logistic Regression accuracy:", log_grid_search.best_score_)

# Set up the parameter grid for Decision Tree
dt_param_grid = {
    'max_depth': [None, 3, 5, 7, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Run GridSearchCV for Decision Tree
dt_grid_search = GridSearchCV(DecisionTreeClassifier(random_state=42), dt_param_grid, cv=5, scoring='accuracy')
dt_grid_search.fit(X_train, y_train)

print("Best Decision Tree params:", dt_grid_search.best_params_)
print("Best Decision Tree accuracy:", dt_grid_search.best_score_)

# Initialize models with best parameters
log_model2 = LogisticRegression(**log_grid_search.best_params_, max_iter=1000, random_state=42)
dt_model2 = DecisionTreeClassifier(**dt_grid_search.best_params_, random_state=42)


# Create Voting Classifier
voting_model = VotingClassifier(
    estimators=[("lr", log_model2), ("dt", dt_model2), ("svc", svc_model)],
    voting="soft"
)

# Train and evaluate
voting_model.fit(X_train, y_train)
voting_pred = voting_model.predict(X_test)
print("Voting Classifier Accuracy with Tuned Models:", accuracy_score(y_test, voting_pred))

"""##Stacking"""

import matplotlib.pyplot as plt
# 4. Stacking Classifier
stacking_model = StackingClassifier(
    estimators=[("rf", rf_model), ("ada", ada_model), ("svc", svc_model)
        ],
    final_estimator=LogisticRegression()  # Meta-model
)
stacking_model.fit(X_train, y_train)
stacking_pred = stacking_model.predict(X_test)
print("Stacking Classifier Accuracy:", accuracy_score(y_test, stacking_pred))
print("\nClassification Report:\n", classification_report(y_test, stacking_pred))
# Generate the confusion matrix
cm = confusion_matrix(y_test, stacking_pred)

# Plot the confusion matrix using seaborn
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False,
            xticklabels=['Healthy', 'Parkinson\'s'],
            yticklabels=['Healthy', 'Parkinson\'s'])
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix for Stacking Classifier")
plt.show()


