# -*- coding: utf-8 -*-
"""1908012_1908029_ ETE-430 Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kmnEIHN96-sumfpi4sjF7F4knvCm69Vy

#parkinson disease detection using RNN, CNN, Ensemble methods
"""

#mount Google
from google.colab import drive
drive.mount('/content/drive')

"""Dataset source:   Max A. Little, Patrick E. McSharry, Eric J. Hunter, Lorraine O. Ramig (2008), 'Suitability of dysphonia measurements for telemonitoring of Parkinson's disease', IEEE Transactions on Biomedical Engineering (to appear).

IMPORT IMPORTANT LIBRARIES
"""

import numpy as np
import pandas as pd
import math
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns
from sklearn.manifold import TSNE
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, VotingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

"""#load Dataset

"""

data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/parkinsons.data", sep=',', index_col='name')
data

"""#Pre processing

"""

#exclude "status" and  from the feature set
X = data.drop('status', axis=1)
# make "status as lebel"
y=data['status']
data.head()

#check for missing value
data.isnull().sum()

y.head()

#check for percentage of class 1(parkinson) and class 0(non-parkinson) data percentage
y.value_counts(normalize=True)

"""#split data into training and testing"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=51)

"""#RNN

"""

!pip install --upgrade tensorflow-estimator
!pip install --upgrade tensorflow-io-gcs-filesystem
!pip install --upgrade tensorflow-metadata

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.optimizers import Adam



# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Reshape for RNN input
X_train_rnn = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
X_test_rnn = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))

# Build the RNN model
model = Sequential([
    LSTM(64, input_shape=(X_train_rnn.shape[1], X_train_rnn.shape[2]), activation='tanh'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train_rnn, y_train, epochs=50, batch_size=16, validation_split=0.2, verbose=1)

# Evaluate the model on test data
test_loss, test_accuracy = model.evaluate(X_test_rnn, y_test, verbose=1)
print(f"Test Loss: {test_loss}")
print(f"Test Accuracy: {test_accuracy}")

"""#CNN

"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical



# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Reshape the data for Conv1D (samples, timesteps, features)
X_reshaped = X_scaled.reshape((X_scaled.shape[0], X_scaled.shape[1], 1))

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y, test_size=0.2, random_state=42)

# Convert labels to categorical (one-hot encoding)
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# Step 2: Define the CNN model
model = Sequential([
     # First Convolutional Layer:Applies 32 filters (feature detectors) of size 3 to the input data.
    # Activation function 'relu' introduces non-linearity to help the model learn complex patterns.
    # 'input_shape' specifies the shape of input data, with (X_reshaped.shape[1], 1) indicating time steps and one feature.
    Conv1D(filters=32, kernel_size=3, activation='relu', input_shape=(X_reshaped.shape[1], 1)),
    MaxPooling1D(pool_size=2),
    Dropout(0.25),
    #2nd Convolutional Layer:Applies 32 filters (feature detectors) of size 3 to the input data.
    Conv1D(filters=64, kernel_size=3, activation='relu'),
    MaxPooling1D(pool_size=2),
    Dropout(0.25),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(2, activation='softmax')  # 2 classes: with and without Parkinson's
])

# Step 3: Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# Step 4: Train the model
history = model.fit(X_train, y_train, epochs=50, batch_size=16, validation_split=0.2, verbose=1)

# Step 5: Evaluate the model on test data
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=1)
print(f"Test Loss: {test_loss}")
print(f"Test Accuracy: {test_accuracy}")

# Step 6: Predict and evaluate
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

# Accuracy, classification report, and confusion matrix
print("Classification Report:")
print(classification_report(y_true_classes, y_pred_classes))

print("Confusion Matrix:")
print(confusion_matrix(y_true_classes, y_pred_classes))

"""#KNN Model"""

#KNN Model
# Reshape X_train and X_test to 2D for KNN
X_train_knn = X_train.reshape(X_train.shape[0], -1)
X_test_knn = X_test.reshape(X_test.shape[0], -1)

# Convert one-hot encoded y_train and y_test back to single-column labels for KNN
y_train_knn = np.argmax(y_train, axis=1)
y_test_knn = np.argmax(y_test, axis=1)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_knn, y_train_knn)  # Use reshaped data for KNN
knn_pred = knn.predict(X_test_knn)  # Use reshaped data for KNN
print("knn Accuracy:", accuracy_score(y_test_knn,knn_pred))  # Use original labels for evaluation
print("\nClassification Report:\n", classification_report(y_test_knn, knn_pred))  # Use original labels for evaluation

X.shape

X.info()

"""#ensembles

##Bagging
"""

# Reshape X_train and X_test to 2D
X_train = X_train.reshape(X_train.shape[0], -1) # -1 infers the remaining dimension
X_test = X_test.reshape(X_test.shape[0], -1)   # -1 infers the remaining dimension

# 1. Bagging with Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
print("Bagging (Random Forest) Accuracy:")
print("\nClassification Report:\n", classification_report(y_test, rf_pred))
print("\nAccuracy Score:", accuracy_score(y_test, rf_pred))

"""##Boosting"""

# Convert y_train to a 1D array if it's one-hot encoded
import numpy as np
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

# Assuming y_test is in multilabel-indicator format, convert to binary format
if y_test.ndim == 2 and y_test.shape[1] > 1:  # Check if y_test is one-hot encoded
    y_test = np.argmax(y_test, axis=1)  # Convert to 1D array of class labels

if y_train.ndim == 2 and y_train.shape[1] > 1:  # Check if y_train is one-hot encoded
    y_train = np.argmax(y_train, axis=1)  # Convert to 1D array of class labels

# 2. Boosting with AdaBoost
ada_model = AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=2),
    n_estimators=150,
    learning_rate=0.5,
    random_state=42)
ada_model.fit(X_train, y_train)  # Now y_train should be 1D
ada_pred = ada_model.predict(X_test)
print("Boosting (AdaBoost) Accuracy:", accuracy_score(y_test, ada_pred))
print("\nClassification Report:\n", classification_report(y_test, ada_pred))

"""##Voting model"""

# 3. Voting Classifier
log_model = LogisticRegression(max_iter=1000, random_state=42)
dt_model = DecisionTreeClassifier(random_state=42)
svc_model = SVC(probability=True,gamma=10, C=1000, random_state=42)

voting_model = VotingClassifier(
    estimators=[("lr", log_model), ("dt", dt_model), ("svc", svc_model),("rf", rf_model),
        ("knn", knn)],
    voting="soft"  # Use 'soft' for probability-based voting
)
voting_model.fit(X_train, y_train)
voting_pred = voting_model.predict(X_test)
print("Voting Classifier Accuracy:", accuracy_score(y_test, voting_pred))
print("\nClassification Report:\n", classification_report(y_test, voting_pred))

"""##voting again with tuned decision tree and logistic regression"""

from sklearn.model_selection import GridSearchCV

# Set up the parameter grid for Logistic Regression
log_param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['lbfgs', 'liblinear']
}

# Run GridSearchCV for Logistic Regression
log_grid_search = GridSearchCV(LogisticRegression(max_iter=1000, random_state=42), log_param_grid, cv=5, scoring='accuracy')
log_grid_search.fit(X_train, y_train)

print("Best Logistic Regression params:", log_grid_search.best_params_)
print("Best Logistic Regression accuracy:", log_grid_search.best_score_)

# Set up the parameter grid for Decision Tree
dt_param_grid = {
    'max_depth': [None, 3, 5, 7, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Run GridSearchCV for Decision Tree
dt_grid_search = GridSearchCV(DecisionTreeClassifier(random_state=42), dt_param_grid, cv=5, scoring='accuracy')
dt_grid_search.fit(X_train, y_train)

print("Best Decision Tree params:", dt_grid_search.best_params_)
print("Best Decision Tree accuracy:", dt_grid_search.best_score_)

# Initialize models with best parameters
log_model2 = LogisticRegression(**log_grid_search.best_params_, max_iter=1000, random_state=42)
dt_model2 = DecisionTreeClassifier(**dt_grid_search.best_params_, random_state=42)


# Create Voting Classifier
voting_model = VotingClassifier(
    estimators=[("lr", log_model2), ("dt", dt_model2), ("svc", svc_model)],
    voting="soft"
)

# Train and evaluate
voting_model.fit(X_train, y_train)
voting_pred = voting_model.predict(X_test)
print("Voting Classifier Accuracy with Tuned Models:", accuracy_score(y_test, voting_pred))

"""##Stacking"""

import matplotlib.pyplot as plt
# 4. Stacking Classifier
stacking_model = StackingClassifier(
    estimators=[("rf", rf_model), ("ada", ada_model), ("svc", svc_model)
        ],
    final_estimator=LogisticRegression()  # Meta-model
)
stacking_model.fit(X_train, y_train)
stacking_pred = stacking_model.predict(X_test)
print("Stacking Classifier Accuracy:", accuracy_score(y_test, stacking_pred))
print("\nClassification Report:\n", classification_report(y_test, stacking_pred))
# Generate the confusion matrix
cm = confusion_matrix(y_test, stacking_pred)

# Plot the confusion matrix using seaborn
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False,
            xticklabels=['Healthy', 'Parkinson\'s'],
            yticklabels=['Healthy', 'Parkinson\'s'])
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix for Stacking Classifier")
plt.show()

"""parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods

parkinson disease detection using RNN, CNN, Ensemble methods
"""